Fix HSL to RGB overflow error
EasyRPG/Player pull request #2323
Opened 2020-09-06 12:58 UTC by rueter37

This PR fixes #2266. If the hue value in the HSL_to_RGB function was greater than or equal to 1536, the color was not converted. Using modulo 1536 on the hue value fixes this because the hue ranges between 0 and 1536 in this function.

2020-09-06 13:37 UTC, fmatthew5876 commented
Going to have to defer to @Ghabry on this one. If he doesn't see anything wrong with the fix than I approve.

2020-09-09 13:28 UTC, Ghabry requested changes
I didn't write this function and it was never touched since 6 years ^^'

Well, the 1536 (0x600) gives some hint about the problem. Thanks for figuring this out.

Imo the real problem is in the function

```cpp
static inline void HSL_adjust(int& h, int& s, int& l, int hue) {
	h += hue;
	if (h > 0x600) h -= 0x600; // <- this must be changed to >=
	if (s > 0xFF) s = 0xFF;
	l = (l > 0xFF) ? 0xFF : (l < 0) ? 0 : l;
}
```

Your modulo is only needed for the ``h = 0x600`` case. For all other values there is now an additional mod operation.
To avoid unnecessary calculations the ``>`` to ``>=`` change is better.

2020-09-09 15:04 UTC, rueter37 commented
Did the requested change now. And thank you for the invitation to the team, very appreciated! :smile:

2020-09-10 09:20 UTC, Ghabry approved these changes
I nuked the first commit and added a warning fix commit

2020-09-10 13:32 UTC, fmatthew5876 approved these changes

2020-09-10 15:02 UTC, merged