Fix random movement behavior on locked face direction
EasyRPG/Player pull request #2447
Opened 2021-01-30 10:53 UTC by rueter37

The random movement behavior uses the current move direction instead of the current face direction now if the face direction is locked. This fixes the bug which disallows the event moving towards the direction he is facing if the face direction is locked and the
movement type is set random movement.

Fixes: #2436

2021-01-30 16:15 UTC, fdelapena approved these changes

2021-01-31 15:26 UTC, fmatthew5876 requested changes
This is actually a larger bug. The Turn90 and Turn180 functions should *always* use direction and not facing. This affects random movement and also the turning move route commands.

Please remove the conditional and change it always use direction. Don't forget to run the unit tests after.

DynRPG Address
-----

| Addr | Name |
| -- | -- |
| 004C45C8 | Turn90DegLeft |
| 004C45F8 | Turn90DegRight |
| 004C4628 | Turn180Deg |

2021-01-31 15:48 UTC, rueter37 commented
Did the requested change. The unit tests were successful.

2021-01-31 17:19 UTC, fmatthew5876 approved these changes

2021-01-31 17:39 UTC, merged

2021-01-31 17:39 UTC, Ghabry commented
Thanks!