WIP: 3DS touchscreen controls toggle
EasyRPG/Player pull request #2617
Opened 2021-08-24 17:33 UTC by troybonneau

Hello! This PR intends to replace the current keyboard on the 3DS touch screen with one that can be toggled. This is accomplished by adding an additional row of buttons and shifting the current interface down a bit. I have this marked WIP because while it is compiling fine I think I am missing a step to get .3dsx files working with the homebrew launcher because it crashes to a black screen on startup. This is my first PR here so any guidance is appreciated! 😄 

![keyboard_on](https://user-images.githubusercontent.com/53018809/130662099-21e87226-9538-4068-8e88-dc1cfeeea2e6.png)

2021-08-25 12:44 UTC, carstene1ns commented
Good work so far.

What I dislike here is the big top row for just disabling the screen. IMO this should be made smaller, so the others buttons only loose a bit of height, I would suggest around 20-26 pixels.
This complicates the button logic a bit, though.
I have an old branch for this, but unfinished... The top row has additional space for example for a battery indicator and a restart(<kbd>F11</kbd>) button.

Code for the battery indicator (drawing in whole, fixed image should be better):
```c++
// in anonymous namespace
u8 battery_charging = 0;
u8 battery_level = 0;
u32 c2d_black = C2D_Color32f(0, 0, 0, 1);
u32 c2d_gray = C2D_Color32f(0.8f, 0.8f, 0.8f, 1);
u32 c2d_white = C2D_Color32f(1, 1, 1, 1);
u32 c2d_red = C2D_Color32f(1, 0, 0, 1);
u32 c2d_orange = C2D_Color32f(0, 1, 1, 1);
u32 c2d_green = C2D_Color32f(0, 1, 0, 1);

// in constructor
ptmuInit();

// in destructor
ptmuExit();

// in processEvents()
PTMU_GetBatteryChargeState(&battery_charging);
PTMU_GetBatteryLevel(&battery_level);

// in UpdateDisplay() when drawing on bottom screen
// battery indicator
int battery_x = 296;
int battery_y = 6;
u32 color = c2d_gray;
if (battery_charging) {
    color = c2d_white;
}
C2D_DrawRectSolid(battery_x, battery_y, 0.5f, 18, 8, color);
C2D_DrawRectSolid(battery_x + 18, battery_y + 3, 0.5f, 2, 2, color);
if (battery_level > 4) color = c2d_green;
else if (battery_level > 2) color = c2d_orange;
else color = c2d_red;
for (int i = 0; i < battery_level; i++)
    C2D_DrawRectSolid(battery_x + 2 + i*2 + i, battery_y + 2, 0.5f, 2, 4, color);
```

2021-08-28 21:07 UTC, Ghabry commented
Reset is already mapped to KEY_SELECT.

I like the proposed solution of Schoko for now (the basic version in the middle)

When the battery indicator is ever added this can be still redesigned again (make everything smaller) in a new PR.

2021-08-31 19:08 UTC, troybonneau commented
![easyrpgkeyboard](https://user-images.githubusercontent.com/53018809/131561517-79c2bb0a-896a-4853-9b89-d37acc89f721.png)

I've adjusted the layout and code to work with the proposed basic version in the middle

2021-08-31 19:14 UTC, Ghabry commented
I do not really understand why you created a new image instead of just taking the one from Schoko but okay...

Imo this is now good enough for inclusion, can you mark the PR as ready?

2021-08-31 19:28 UTC, carstene1ns requested changes

2021-08-31 19:28 UTC, carstene1ns commented on src/platform/3ds/3ds_ui.cpp
> +			if (R_SUCCEEDED(gspLcdInit())) {
Remove first `gspLcdInit()`.

2021-08-31 19:28 UTC, carstene1ns commented on src/platform/3ds/3ds_ui.cpp
> +				gspLcdInit();
Please also with error checking.

2021-08-31 20:03 UTC, carstene1ns approved these changes
Okay for now.

2021-08-31 20:04 UTC, fdelapena approved these changes

2021-08-31 20:12 UTC, Ghabry commented
jenkins: test this please

2021-08-31 21:12 UTC, carstene1ns commented on src/platform/3ds/3ds_ui.cpp
> +		u8 draw_width = button_width;
instead simply replace it

2021-08-31 21:15 UTC, carstene1ns commented
jenkins: ok to test

2021-08-31 21:21 UTC, carstene1ns commented
Looks good to squash and merge 👍🏼

2021-08-31 21:25 UTC, troybonneau reviewed
Alright looks like everything is building well. Ready on my end.

2021-09-02 01:05 UTC, merged