WiiU Fixes
EasyRPG/Player pull request #3234
Opened 2024-06-02 22:34 UTC by Ghabry

Still lacks polish like e.g. a nice banner but at least audio does not assert anymore and saving of the config works.

----

About this weird teardown in player.cpp (can we do better?)

SDL2 has a ProcUI handle which refers to the current application and for a proper shutdown of the app, SDL2 listens to PROCUI_STATUS_EXITING and then does some further cleanup.

When using the Exit menu item this will not trigger the cleanup automatically because SDL will not receive the shutdown event (but it receives it when using "WiiU Menu" in the home menu).

To make it receive the event I call ``SYSLaunchMenu()``, then pump events once more (via that recursive call, SDL gets the quit event now) and then everything works...

https://github.com/devkitPro/SDL/blob/7b058bd042a7c624c277aaddbca6fb2f6ae5233d/src/video/wiiu/SDL_wiiuvideo.c#L326-L338

2024-06-02 23:53 UTC, carstene1ns commented
The `SysLaunchMenu()' call is a good workaround, using this now as well:
https://github.com/carstene1ns/easyrpg-player/blob/956eb50afcb5cbd624ad94d237d2bfa9b4405bed/src/platform/wiiu/main.cpp#L121-L131

And here is the rest of the WIP branch:
https://github.com/EasyRPG/Player/compare/master...carstene1ns:easyrpg-player:feature/wiiu

You can use this network log receiver for debugging: https://gist.github.com/carstene1ns/e38fa10351449fee25cf2cc339c8e043

2024-06-03 12:22 UTC, Ghabry commented
woah that UDP logger is awesome. Makes my life much easier xD

2024-06-03 14:14 UTC, Ghabry commented
Your code terminates fine when using the exit option but exiting from the WiiU menu crashes in most cases :/

Haven't found a working solution yet.

---

My ugly recursive call on exit is working in both cases

2024-06-03 17:54 UTC, Ghabry commented
Shutting down works now properly in all three cases:

- Home Menu
- Player picks Exit
- Output::Error

The only remaining problem is extremly slow opening of ZIP archives, likely some IO buffering issue. But is not a _blocker_ for me.

----   

Had to replace these WHB wrapper functions with calls to ProcUI which is the low level API.

SDL2 will not handle it when it is initialized before launching SDL2. (see code in wiiu_video.c)

Problem is that you cannot query the ProcUI status after it was shutdown (calling the function will crash) so I needed more low level access to differentiate between "Home Menu used" and "Exit option selected (or Output::Error)".

(This also makes ``WHBProcIsRunning`` crash when the shut down was requested, making this function pretty useless for checking whether it is running xD)

---

btw it seems USB Keyboards are not initialized by SDL2/WUT, so cannot use it :(  (used it to input the Wifi password before so should work in theory...)

2024-06-03 18:01 UTC, Ghabry commented
![IMG_20240603_143132](https://github.com/EasyRPG/Player/assets/1331889/d45902a5-f5f5-441f-8563-c7d119c64b0d)

![IMG_20240603_143145](https://github.com/EasyRPG/Player/assets/1331889/72114f53-22a2-4ee7-9fdb-3da72d2d1831)

![IMG_20240603_143147](https://github.com/EasyRPG/Player/assets/1331889/37f83e3c-aab7-4404-872d-0b68f9a822ce)

2024-06-03 19:20 UTC, carstene1ns commented on resources/wiiu/splash-drc.png
Calling @jetrotal for a higher quality version of the drc splash, this one has been upscaled.
Also we could drop the black border of the icon...

2024-06-03 20:06 UTC, Ghabry commented on resources/wiiu/splash-drc.png
The Logo Text indeed needs a bigger version.

For the rest:

There is a PSD file in https://easyrpg.org/downloads/logos/ Gimp can load it but is not fun working with it :sweat_smile: 

For the splash this could be used (?) Has the same metrics as the real logo, just higher res.

![splash-drc](https://github.com/EasyRPG/Player/assets/1331889/c12d7d38-8300-4ed2-afe3-2be7fb4554a2)

Or this:

![Unbenannt](https://github.com/EasyRPG/Player/assets/1331889/9211185f-bc61-4893-be42-4fe96a312d97)


Icon:

![icon](https://github.com/EasyRPG/Player/assets/1331889/bd415795-b02f-4535-8209-53ee6a051703)

Unfortunately the EasyRPG text is hard to read here as it is too bright (gray Ui on WiiU)

So Icon with text works better:

![icon](https://github.com/EasyRPG/Player/assets/1331889/0330a065-c93a-44de-933c-a7858c813517)

2024-06-03 20:23 UTC, Ghabry commented
The ICU issue is a simple fix :confetti_ball:  :confetti_ball:   :confetti_ball: 

The patch must be moved before ``cp -rup icu icu-native`` as the tool that requires patching is from the native icu.

https://github.com/EasyRPG/buildscripts/blob/master/wiiu/2_build_toolchain.sh#L45

2024-06-04 09:58 UTC, jetrotal commented
icon
![image](https://github.com/EasyRPG/Player/assets/45118493/d7dd42b5-69f5-431e-8393-fda77b1cd16d)

TV
![image](https://github.com/EasyRPG/Player/assets/45118493/6bef69a0-457a-420b-9c4c-d0d1ef3a1af9)

PAD
![image](https://github.com/EasyRPG/Player/assets/45118493/e7b9d18b-aa8a-4646-8374-4322beefe665)


----------------------------------

The idea is to promote ourcharsets on the joypad screen, by letting a user search for their favorite character by looking at it.


Here's a psd containing editable assets:
[EasyRP_wiiu_PSDs.zip](https://github.com/user-attachments/files/15546242/EasyRP_wiiu_PSDs.zip)

I recomend opening my psd files over the browser editor https://www.photopea.com/
instead of GIMP.

2024-06-04 10:17 UTC, Ghabry commented
Thanks!

The downscale made imo Y look weird because on one side it is one pixel shorter.

Quickly edited it:

![grafik](https://github.com/EasyRPG/Player/assets/1331889/ebea8464-112d-4c89-9473-a037cd895c03)

2024-06-04 17:11 UTC, Ghabry commented
Somehow the buffering doesn't work and "pubsetbuf" does nothing (which is allowed by the standard xD) so I wrote my own buffering file IO.

Verifying whether the filebuf implementation is correct is a bit tricky. I wrote a test code that does hundreds of random seeks using beg/cur/end mode and reads and compared the result with the normal fstream.

Then executed it multiple times until I got no asserts anymore because of mismatches...

2024-06-05 07:04 UTC, Ghabry commented
I will enable this custom IO for the other homebrew targets.

Only did an additional test on the Wii and this gives a huge loading time speedup. So likely also helps on Vita, 3DS and Switch.

2024-06-10 20:29 UTC, carstene1ns requested changes
Apart from a few nits, works really great now!

2024-06-10 20:29 UTC, carstene1ns commented on src/platform/wiiu/main.cpp
> +using namespace std::chrono_literals;
This once could go or let it stay and change in `WiiU_Exit()`.

2024-06-10 20:29 UTC, carstene1ns commented on src/platform/wiiu/main.cpp
> +static bool prodUiExited = false;
This needs to be moved above the `#ifdef NDEBUG` in line 38 and should be changed to `procUiExited`.

2024-06-10 20:29 UTC, carstene1ns commented on src/platform/wiiu/main.cpp
> +		Game_Clock::SleepFor(std::chrono::milliseconds(10));
Could be `10ms`.

2024-06-10 20:29 UTC, carstene1ns commented on src/platform/wiiu/main.cpp
> +		//args.push_back("--save-path");
This should have a `// FIXME: shipped game has nowhere to save` 🐧

2024-06-10 20:29 UTC, carstene1ns commented on src/player.cpp
> +#if defined(__WIIU__)
I had these applet lifetime checks moved from here for the 3DS and switch ports, no real need to add a platform dependency here.
See also https://github.com/EasyRPG/Player/commit/c9b1809898bfb687cd2e775710187887ec146729#diff-10c39dd978ada90e0d090a045c4ae5f51dad010f3b754679e15894c9b93d254b

2024-08-27 17:44 UTC, Ghabry commented
Jenkins: test this please

Addressed the review comments and fixed a few more minor bugs. Is ready now :+1:

2024-08-27 20:11 UTC, fdelapena approved these changes

2024-09-02 14:49 UTC, merged